version: '2.4'
services:

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - CHROME_DRIVER_VERSION=chromedriver_81.0.4044.69

  protractor:
    image: node:12.14
    container_name: protractor
    ports:
      - "9229:9229"
    command: bash -c "apt update && apt install -y git && git clone -b main https://github.com/AlfredoBazo/opwDocker.git && cd opwDocker && npm install && node node_modules/protractor/bin/protractor e2e-tests/protractor.conf.js --cucumberOpts.tags=@todo"
    depends_on:
      - selenium-hub
      - chrome
