version: "3"

services:
  blockchain:
    image: trufflesuite/ganache-cli:latest
    container_name: Ganache
    command: --deterministic --defaultBalanceEther 10000
    ports:
      - 8545:8545
    restart: always

  dapp:
    build: .
    container_name: DAPP
    ports:
      - 3000:3000
    volumes:
      - app:/app
    depends_on:
      - blockchain

volumes:
  app:
