version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    restart: always
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    networks:
      - tfg

  reverse-proxy:
    image: jc21/nginx-proxy-manager
    container_name: Reverse-Proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx-proxy-manager-data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - tfg

  cloud:
    image: nextcloud
    container_name: NextCloud
    restart: always
    links:
      - db
    ports:
      - 88:80
    volumes:
      - nextcloud:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=Welcome123456789
      # - NEXTCLOUD_DATA_DIR=/media/
      - NEXTCLOUD_TRUSTED_DOMAINS= localhost
      - TRUSTED_PROXIES=reverse-proxy
      - OVERWRITEPROTOCOL=https
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Welcome123456789
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=db
    networks:
      - tfg

  db:
    image: mariadb:10.6
    container_name: MariaDB
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Welcome123456789
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - tfg

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    networks:
      - tfg

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: Wireguard
    restart: always
    volumes:
      - ./wireguard-config:/config
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # - SERVERURL=wireguard.domain.com #optional
      # - SERVERPORT=51820 #optional
      - PEERS=5 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.10.10.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  pihole:
    image: pihole/pihole:latest
    container_name: Pi-Hole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "Welcome123456789"
    networks:
      - tfg

volumes:
  mariadb-data:
  nextcloud:
  nextcloud-apps:
  nextcloud-config:
  nextcloud-data:
    external: true

networks:
  tfg:
    driver: bridge
