version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    restart: always
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
    networks:
      - tfg

  reverse-proxy:
    image: traefik:v2.10
    container_name: Reverse-Proxy
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
    networks:
      - tfg

  cloud:
    image: nextcloud
    container_name: NextCloud
    restart: always
    links:
      - db
    ports:
      - 88:80
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.rule=Host(`cloud.localhost`)"
      - "traefik.http.routers.cloud.entrypoints=http"
      - "traefik.http.routers.cloud.tls=true"
      - "traefik.http.routers.cloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.cloud.loadbalancer.server.port=80"
      - "traefik.docker.network=tfg"
      # - "traefik.http.routers.cloud.middlewares=cloud-dav,default@file"
      # - "traefik.http.middlewares.cloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      # - "traefik.http.middlewares.cloud-dav.replacepathregex.replacement=/remote.php/dav/"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=Welcome123456789
      # - NEXTCLOUD_DATA_DIR=/media/
      - NEXTCLOUD_TRUSTED_DOMAINS= localhost cloud.localhost
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Welcome123456789
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=db
    networks:
      - tfg

  db:
    image: mariadb:10.6
    container_name: MariaDB
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Welcome123456789
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - tfg

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 1111:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=https"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=http"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=tfg"
      - "traefik.http.routers.phpmyadmin.middlewares=default@file"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_PASSWORD: root
    networks:
      - tfg

  pihole:
    image: pihole/pihole:latest
    container_name: Pi-Hole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.localhost`)"
      - "traefik.http.routers.pihole.entrypoints=http"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "Welcome123456789"
    networks:
      - tfg

volumes:
  db:
  nextcloud:
  apps:
  config:
  data:

networks:
  tfg:
    driver: bridge
